### ISSUE TITLE
Simpler approach in psake.ps1

### ISSUE THREAD

**Issue by nightroman** [devblackops/psake.module.tasks#1]
I did not try this but it looks like it is possible to remove

```powershell
    $script:testTask = Get-TestTask
    $script:deployTask = Get-DeployTask
```

and define tasks as

```powershell
    task Test -depends Init (Get-TestTask)
    task Deploy -depends Test (Get-DeployTask)
```

**Comment by devblackops** [comment]
Possibly. I'll have to try it out. I was under the assumption I would run into all sorts of scope issues but I spent all of about 20 minutes putting this together 😄

**Comment by nightroman** [comment]
Closing, this is not really an issue.

I am looking forward to the further development. I tried something like this in the past and was not impressed by the results. I would like to know the advantages of exporting something in "task-like" form instead of exporting just regular functions designed "for calls from tasks".
